### ISSUE TITLE
Repository maintenance

### ISSUE THREAD

**Issue by crosire** [scripthookvdotnet/scripthookvdotnet#1222]
I don't currently have the resources and motivation to actively maintain this repository, and also haven't contributed many changes recently. That award most certainly goes to @kagikn. Plus I generally agree with all those changes, as such it IMHO makes sense to give @kagikn full decision power on pull requests and releases, without having to wait for my approval (I'd just like to reserve participation in changes to the `ScriptDomain` core). That way this project is less hindered by slow response times from myself. So please feel free to go ahead with changes without me chiming in if you want!

Note, that I think it would also make sense to change the release creation authentication token to this end, so that new releases are credited to the correct user:
https://github.com/crosire/scripthookvdotnet/blob/52ef1866141c6368b68d31ca776e3cbaae9ff879/appveyor.yml#L40

**Comment by kagikn** [comment]
I appreciate the explicit approval, which enables me to change APIs (most likely new additions) without the explicit approval of @crosire !

Maybe I might not be actively adding new features after v4 is released and I would be creating a new variant made with .NET 7+ then (I don't like 3 year support even with LTS, but too many great changes to bear). Maybe I would create a new variant for RDR2 because [ScriptHookRDR2DotNet](https://github.com/Halen84/ScriptHookRDR2DotNet-V2) by Saltyq (the original variant) and Halen84 doesn't make much attention and script developers doesn't bother to use it and create scripts using the API of ScriptHookRDR2.

Still, I'd like to maintain this repository in bug fixes, new game version support, and performance improvement even if my primary motivation goes to other projects. I would appreciate bug reports by other people though, especially if some game update break some functionality or compatibility or some changes in this repository breaks something in unintended ways (we would say like "it's intended change" or "excepted changes" if we do change something in intended ways).

**Comment by kagikn** [comment]
I'm thinking of using GitHub organizations just like FiveM uses [Cfx.re](https://github.com/citizenfx) organization, what do you think?
If would be great if we could receive donation from generous people, but I don't have any ideas for its rewards. Man, I'm jealous of FiveM having more than 10000 patrons on Patreon.

**Comment by crosire** [comment]
I can look into doing an organization and transfering the repo there. Just a bit worried that existing links to this repository would break.
In my opinion you don't necessarily have to have rewards for Patreon if its made clear that development effort goes into the open source project and as such it's not that feasible to have have something limited to Patreons, instead it would just be a monetary way to say thank you (I do something like that for ReShade).

GitHub Actions makes sense I think. AppVeyor was used initially because GitHub Actions didn't exist back then. But it's now comprehensive enough that AppVeyor ahould no longer be needed. Just that like with the rest it would be effort to change it and so was easier to just leave things how they were for the time being.

The 5Mods download page can't be transferred according to them unfortunately. My account there got compromised a while back because I hadn't properly secured it and while that was all resolved with the mod team using a new one, the old banned one was renamed and archived, but still holds ownership of the SHVDN page and for technical reasons it can't be transferred to the new one apparently. So I can't update that anymore either.

**Comment by kagikn** [comment]
@crosire It would be great if a secret environment for NuGet API was configured for #1225 since I can't edit secret variables and I'm not a owner of NuGet packages of APIs (probably an api key for GitHub releases should be configured as well) if you don't plan to transfer the ownership to an organization (or me?).
I have NuGet account, so you can invite me as a new owner of API packages. If I get a ownership, I would deprecate the package of v2 API to suggest script devs migrate to v3 (I see a lot of new scripts built against v2 even today).

**Comment by crosire** [comment]
Invites are sent. Project was also moved to an organization now (old links continue to work).

**Comment by kagikn** [comment]
I appreciate the invitations for NuGet packages, but there are more things I want to ask you for. I should have realized these before asking though.
- May I have my admin role for this repo? I have to get the ability to read/write access to security before I can have workflow(s) create a new release via GitHub Actions.
- May I have my admin role for [scripthookvdotnet-nativege](https://github.com/scripthookvdotnet/scripthookvdotnet-nativegen)? Or may I have my maintain (or write) access if my admin role is unacceptable? I don't even have the write access for the nativegen repo now. I can create a new repo for native generator within the organization, but that would lead people to confuse.
- Lastly, may I be one of the organization owners of the organization (not just as a member)? If unacceptable to assign me as a organization owner, may I be a organization moderator so I can hide comments? You can few more things with your organization moderator role than a member role, so it would be great if I got a owner role for the organization.

I appreciate your hard work for SHVDN you have done, really. I feel like I should provide the contribution guide so more people will try to contribute to this project btw.

**Comment by crosire** [comment]
@kagikn Should be fixed now!

**Comment by kagikn** [comment]
maybe it's good time to close i guess
