### ISSUE TITLE
Please change attributes  names order  string animName and  ClipDictionary clipDictName in public abstract class Entity .

### ISSUE THREAD

**Issue by ILaCHu** [scripthookvdotnet/scripthookvdotnet#1271]
In  public abstract class Entity  void names attributes  has not a same order like another  
Needed Standardization fist    ClipDictionary then clipDictName  in StopAnimation , PlayAnimation ,

**Comment by kagikn** [comment]
I keep the same order as the native definitions for new wrapper methods being introduced in v3.7.0, so you won't get confused when you use `Function.Call` directly or when you code scripts under other environments such as C++ scripts for ScriptHookV or some scripts for FiveM. I don't think there's too much of issues in parameter orders if we keep the same orders as the native definitions. Also, [you can specify the arguments by variable names](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#named-arguments).

Despite my opinion about parameter orders of the new methods, however, maybe an implicit operators of `ClipDictionary` is making the confusion, so I'm going to change it to an explicit one and see if the pitfall is gone.

**Comment by kagikn** [comment]
6b50fdc procects you from dumb mistakes in how you determine arguments to pass. No more pitfalls to make dumb mistakes in methods like `Entity.PlayAnimation` due to implicit type conversions. Still you can cast values to another type you want, like you can explicitly convert string to a clip dictionary struct just like `(ClipDictionary)clipDictStr`.
