### ISSUE TITLE
Dedicated GameClockDateTime

### ISSUE THREAD

**Issue by kagikn** [scripthookvdotnet/scripthookvdotnet#1281]
While built-in .NET `System.DateTime` doesn't make sense for the GTA clock due to how wide range the game can handle the date time in, maybe we can create the custom struct `GtaDateTime` that can handle any range of date time in GTA system? The game can handle leap years and years more than 10000 or negative (though the game will suffer a lot of fps loss you put like 10^7 to the year of the date).

**Comment by nomakewan** [comment]
This would be absolutely freaking amazing if you can pull it off.

At the moment, BTTFV uses System.DateTime for everything. Which works until you get into the weird stuff (like people wanting to visit year 0000 since that's referenced in Back to the Future itself, or trying to watch the clock tick over on December 31 9999). If however SHVDN exposed a totally separate DateTime paradigm, we could finally allow users to input those times without the workarounds we've been using to prevent script crashes so far.

As far as limits go, we only have a four-digit year display with no sign. So at least as far as our mod goes, excessively negative years, or years excessively beyond 9999 are unnecessary. We'd just work out a "glitchy year display" if you're before 0000 or after 9999, and only actually allow the user to type years between 0000 and 9999. In this way the user can't actually input negative years or year 10000+, but if they coincidentally end up in those years, it won't crash the script and there'll still be a way out of the situation.

So yeah, this would be really awesome!

**Comment by kagikn** [comment]
I found the game function to update the month and year, which is called the game update the minute value. If we replicate most of the logics used in the function, we could normalize internal values for date time structs on construction so date calculation won't go wrong. The said function which can be found with `39 43 04 7F E0 EB 27 8B 43 08`.

**Comment by kagikn** [comment]
I am speculating handling month values not in the range of 0 to 11 would requires cafeful work, so let us skip the custom struct in v3.7.0.
You could test the `NormalizeDate` below to see if it can handle arbitrary values for day values.
```cs
// Functions like the date update function in the game.
// Put a value in the range of 0 to 11 to inputMonth, no other values as the game goes outside of the array for the numbers of days in months!
private static void NormalizeDate(int inputDay, int inputMonth, int inputYear, out int retDay, out int retMonth, out int retYear)
{
	retDay = inputDay;
	retMonth = inputMonth;
	retYear = inputYear
	for (int i = retMonth; ; i = retMonth)
	{
		int dayInMonth = GetDayInMonth(i, retYear);
		if (retDay <= dayInMonth)
			break;
		retDay -= dayInMonth;
		NormalizeYearAndMonth(retMonth, retYear, 1, out retMonth, out retYear);
	}
	while (retDay <= 0)
	{
		int targetMonth = retMonth;
		if (retMonth != 0)
		{
			targetMonth -= 1;
		}
		else
		{
			targetMonth = 11;
			--retYear;
		
		retDay += GetDayInMonth(targetMonth, retYear);
		NormalizeYearAndMonth(retMonth, retYear, -1, out retMonth, out retYear);
	}

private static void NormalizeYearAndMonth(int inputMonth, int inputYear, int diffMonth, out int resMonth, out int resYear)
{
	resMonth = inputMonth + diffMonth;
	resYear = inputYear;
	if (resMonth > 11)
	{
		do
		{
			resMonth -= 12;
			++resYear;
		}
		while (resMonth > 11);
	}
	if (resMonth < 0)
	{
		do
		{
			resMonth += 12;
			--resYear;
		}
		while (resMonth < 0);
	}

public static bool IsLeapYear(int year)
{
	return (year % 4) == 0 && year != 100 * (year / 100) || year == 400 * (year / 400);

private static int GetDayInMonth(int monthZero, int year)
{
	return IsLeapYear(year) ? DaysInMonth366[monthZero] : DaysInMonth365[monthZero];

private static byte[] DaysInMonth365 => new byte[] { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
private static byte[] DaysInMonth366 => new byte[] { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
```

**Comment by kagikn** [comment]
Actually, I'm implementing chrono stuff because I started to think it's invaluable. The b2699 exe has the strings `GameClockHour`, `GameClockMinute`, `GameClockSecond`, `GameClockDay`, `GameClockMonth`, and `GameClockYear`. And I'm adding `GameClockDuration`, `GameClockDate`, `GameClockTime`, and `GameClockDateTime`, while I'm looking at how local date time classes of [time-rs](https://github.com/time-rs/time) and [Noda Time](https://github.com/nodatime/nodatime) are implemented... and how the classic Java 8 Date Time API are implemented, a bit.

`GameClockDuration` would hold a i64 value to represent the duration since the epoch which is January 1st, year zero. It can even represent duration offset from January 1st, year -0x80000000 to December 31st, year 0x7FFFFFFF, and vice versa. `GameClockDate` would contain a i32 year (uses full bits of signed i32 because the game's time functions use signed instructions without range restrictions, not unsigned variants) and probably a ordinal value of day of year.
