### ISSUE TITLE
SHVDN prevents game from shutting down properly

### ISSUE THREAD

**Issue by DMGT4** [scripthookvdotnet/scripthookvdotnet#1302]
I'm a complete novice in terms of modding V so forgive me if I'm wasting your time.

As the title says, after quitting the game, be it pause -> game -> exit or through Alt+F4, the process hangs in the background and has to be manually closed through R* Launcher.
This sounds like an issue already reported here https://github.com/scripthookvdotnet/scripthookvdotnet/issues/1063
except this happens every time, even without any tools/mods/scripts installed besides scripthook, SHVDN, ASI loader and their prerequisites like redists/runtimes.
If I remove all files belonging to SHVDN from the game's folder, it will close properly.

Like I said, I'm a novice here so I'm at a complete loss as to why this happens.

**Comment by nomakewan** [comment]
Are you using the latest build from https://github.com/scripthookvdotnet/scripthookvdotnet/actions/runs/5814891576 ?

Because if you are referring to the public releases (3.6.0 and older), yes, this is a known issue. However, it has long since been resolved in the nightly builds (and will be included of course in 3.7.0).

**Comment by DMGT4** [comment]
Thank you very much, the nightly build does indeed fix the problem.
