### ISSUE TITLE
[Bug]: GameClockDate.WithYear throws NoFeb29NonLeapYear even if issue isn't a leap year

### ISSUE THREAD

**Issue by nomakewan** [scripthookvdotnet/scripthookvdotnet#1348]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

 a69b254

### Game Version

v1.0.3028.0

### Bug Description

When GameClockDate.WithYear() fails for _any_ reason, it throws a leap year exception. This can be a red herring for script programmers who might not think to tear into SHVDN's WithYear() function to see what's going on.

In my instance, I was migrating code from System.DateTime to GameClockDateTime, and was attempting to use WithYear to move the DateTime January 21, 1981 00:00 to January 21, 1991 00:00. When I fired up the game, the script crashed with a leap year exception, which confused me for a bit since neither year was a leap year nor did either date deal with February 29.

Then I realized the actual issue was that we were pulling data from a serialized XML file that had previously used System.DateTime, so when that older XML was read back, it was passing invalid data into a GameClockDateTime object which then was asked to have WithYear() run on it. Since the result of `GameClockDate? newDate = FromMdf(year, mdf)` is therefore null, the code assumes that the only reason it can be null is if the user attempted a leap-year-related operation incorrectly and so throws a leap year exception rather than an exception related to the invalid (null) base input data.

Removing the XML file resolved our issue, and since GameClockDateTime is not serializable we have reverted to System.DateTime for this specific use case (it was for performing ambient vehicle model swapping which allowed user-provided XML files to define said swaps including restricting them to specific time periods, and since vehicles are only really valid for the 20th century onwards we can get away with System.DateTime's limitations).

### Steps To Reproduce

1. Create a GameClockDateTime with an improper value (for example, null).
2. Attempt to call GameClockDateTime.WithYear(1991) on it.

### The Current Behavior

NoFeb29NonLeapYear Exception is thrown.

### The Expected Behavior

An Exception related to the null/malformed GameClockDate is thrown.

**Comment by kagikn** [comment]
I know you can create an invalid `GameClockDate` and `GameClockDateTime` with setting to `default`, but I wonder how you can create one in another way? An code example would help others including me easily unterstand what the issue is like.

**Comment by nomakewan** [comment]
I added code examples to the issue for your reference. Thanks for the swift solution!

**Comment by kagikn** [comment]
@nomakewan Since you reported this issue with your use case related to a serialized XML for FusionLibrary, I just tested adding `[Serializable]` to `GameClockDate`, `GameClockTime`, and `GameClockDateTime` to see if the library script could deserialize date time members as `GameClockDateTime`, thinking that that will fail without defining how to parse. And no, just adding the serializable attribute to the 3 date time struct doesn't let the library deserialize properly, just all the internal members got inited with zero values. You can see how the date time members are deserialized with the following lines at [the line 64 in TrafficHandler.cs at the commit 7dbb358](https://github.com/nomakewan/FusionLibrary/blob/7dbb358069309c9dab59fd9352979a51af4473de/Traffic/TrafficHandler.cs#L64).
```cs
GameClockDateTime startDt = modelSwap.StartProductionDate;
GTA.UI.Notification.PostTicker($"StartProdDate: {startDt.Year}-{startDt.Month}-{startDt.Day}T{startDt.Hour}:{startDt.Minute}:{startDt.Second}", false, true);
GameClockDateTime endDt = modelSwap.EndProductionDate;
GTA.UI.Notification.PostTicker($"EndProdDate: {endDt.Year}-{endDt.Month}-{endDt.Day}T{endDt.Hour}:{endDt.Minute}:{endDt.Second}", false, true);
```
I guess you need to seek for how to parse a xml in your own way. Good bug finding wrt to this issue though.
