### ISSUE TITLE
Function to add or replace labels during runtime

### ISSUE THREAD

**Issue by justalemon** [scripthookvdotnet/scripthookvdotnet#1380]
FiveM has [AddTextEntry](https://docs.fivem.net/natives/?_0x32CA01C3) and [AddTextEntryByHash](https://docs.fivem.net/natives/?_0x289DA860) to set the text of labels during runtime, I feel that this would be a useful feature to have.

**Comment by kagikn** [comment]
In short: we could stay away from dynamic text insertion until a separate asi is made for that purpose with mutex locking. Some script modders who prefer C++ might want that features as well.

This may sound surprising, but creating a separate asi would be better for dynamic text insertion, before adding equivalent methods of `AddTextEntry` and `AddTextEntryByHash` in FiveM. Both FiveM and RAGENativeUI (RNUI) adds such features by adding custom code. I couldn't find functions for adding text entries to `CTextFile` (which gxt2 text entries are in) in the source code, either.

FiveM's custom code:
https://github.com/citizenfx/fivem/blob/030778a167242f79e0f59cd8d9c04b970e3b75c2/code/components/citizen-resources-gta/src/TextChangingFunctions.cpp#L22-L120
https://github.com/citizenfx/fivem/blob/030778a167242f79e0f59cd8d9c04b970e3b75c2/code/components/gta-core-five/src/CustomText.cpp#L39-L56

RNUI's custom code:
https://github.com/alexguirre/RAGENativeUI/blob/7a9066455a96638a9845bbd87b51467c68d58996/Source/Localization.cs#L126-L144
https://github.com/alexguirre/RAGENativeUI/blob/7a9066455a96638a9845bbd87b51467c68d58996/Source/Internals/Memory.cs#L588-L632

Since the game uses the global `CTextFile` named `TheText` for text entry functions, it's best to use a mutex to avoid potential data race or race condition when mutating `TheText`. Some script modders who prefer C++ might want to add their texts to that variable, too. I should not add the features without proper synchronization...
