### ISSUE TITLE
[Bug]: Exception Occurred while executing   ScriptHookVDotNet.asi (0x00007FFFE19625B0), id 44

### ISSUE THREAD

**Issue by OutLawLowe** [scripthookvdotnet/scripthookvdotnet#1402]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

d955e2a

### Game Version

v1.0.3095.0

### Bug Description

CORE: An exception occurred while executing
"ScriptHookVDotNet.asi (0x00007FFFE19625B0), id 44
Press OKto continue.

### Steps To Reproduce

1.) Just installed Script hookv and nightly vdotnet, and simple hud and lemon Ui, when i launch LSPDFR it says the error code.

### The Current Behavior

When i go to launch LSPDFR it says CORE: An exception occurred while executing
"ScriptHookVDotNet.asi (0x00007FFFE19625B0), id 44
Press OKto continue. 

then simplyhud wont work

### The Expected Behavior

To load ScriptHookVDotNet.asi

**Comment by kagikn** [comment]
Probably the same bug as #1401, but I'll leave this open for now as I'm not completely sure.

**Comment by OutLawLowe** [comment]
so in his instance he said he disabled the upscaler? Im not running a graphics pack atm i deleted it and redid everything after for lspdfr again and still getting this error with ScriptHookVDotNet.asi erroring.

**Comment by OutLawLowe** [comment]
![Screenshot 2024-02-12 005816](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/159752201/72ebb7db-c0cb-46e7-9e2b-31a6812126fd)

**Comment by kagikn** [comment]
> so in his instance he said he disabled the upscaler? Im not running a graphics pack atm i deleted it and redid everything after for lspdfr again and still getting this error with ScriptHookVDotNet.asi erroring.

I don't think the upscaler is not really relevant now, even if removing it happened to stop causing the error in his game. I believe there's still other multithreading bugs, but ones that involves data races or race conditions are non-deterministic and I haven't reproduced this issue once (this doesn't prove there's no bugs involving them though)…

**Comment by OutLawLowe** [comment]
Yeah i got it orginally, so i deleted GTA complelety and just resintalled and added LSPDFR and SimpleHud and error still remains, so with that any idea on how to fix the issue, the very first time i started it worked then when i closed and reopened its been this error ever since.

**Comment by OutLawLowe** [comment]
i installed NVE and then it started randomly working and then once i reopened the game right after it got the same error.

**Comment by HotCandy69** [comment]
I've got the exact same issue. Tried both Nightly-60 and -59. The game worked just fine the first time I launched it with Nightly-60 and ever since then I keep getting the repeat of the error during loading:

Although the exception code is slightly different in numbers, no idea if that matters:

[21:40:12] CORE: An exception occurred while executing 'ScriptHookVDotNet.asi' (0x00007FF9B21B2680), id 38

**Comment by HotCandy69** [comment]
Alright, just quick update. I was suggested at RAGE Discord to try nightly-37 and that one worked, not sure if this bit of info helps you in any way though.

**Comment by nomakewan** [comment]
> Alright, just quick update. I was suggested at RAGE Discord to try nightly-37 and that one worked, not sure if this bit of info helps you in any way though.

37 didn't do anything related to the core. In fact, the majority of commits around 37 were all related to documentation, not code. As a result, you should be able to run Nightly-44 just as easily as Nightly-37. Nightly-45 introduced the first Core update since -37, so my guess is that's where you'll actually see a difference.

Feel free to test it yourself.

**Comment by kagikn** [comment]
I believe this issue is already resolved as how #1454 got resolved.
