### ISSUE TITLE
[Bug]: GTA V crash mid loading screen with RAGE

### ISSUE THREAD

**Issue by Demons-Angel** [scripthookvdotnet/scripthookvdotnet#1413]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

v3.6.0

### Game Version

v1.0.3095.0

### Bug Description

 GTA V at mid loading screen with RAGE and SHVDN. Also when start normal and open the RAGE console (F4) it crash. 

### Steps To Reproduce

 SHVDN crash without an error just deleting the files.

### The Current Behavior

when start normal and open the RAGE console (F4) it crash.

### The Expected Behavior

GTA V load perfectly and RAGE console (F4) it should work as normal.

**Comment by kagikn** [comment]
You should try [nightly builds](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases) instead of v3.6.0 if you want to use SHVDN along with RAGE Plugin Hook. You could use v3.7.0 or later versions after v3.7.0 gets released. v3.6.0 and any earlier stable versions suffer the compatibility issues with RAGE Plugin Hook (see #976 for details).

If you don't encounter some compatibility issues with RAGE Plugin Hook when you run a nightly version of SHVDN, I'll close this issue as  invalid one.

**Comment by Demons-Angel** [comment]
I tried nightly version it didn't work still same issue. About SHVDN v3.7.0 is it released?!!
