### ISSUE TITLE
[Bug]: Animation Flags missing?

### ISSUE THREAD

**Issue by bbodhix** [scripthookvdotnet/scripthookvdotnet#1418]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

3.6.0

### Game Version

V1.68

### Bug Description

There is Animation Flags in Dot Net 3 that I can’t use

### Steps To Reproduce

I can literally a lot of Animation Flags that I can’t use  in DotNet 3 dictionary but when I set one and got into the game Script Hook says that GTA.AnimationFlags does not contain that definition, it only works with the DotNet 2 Flags, but that flags are just like 6 and there is no the flag that I want

### The Current Behavior

Si with this bug I can’t make my script

### The Expected Behavior

I am I doing something wrong or this actually a missing flags?

**Comment by kagikn** [comment]
I believe there's nothing wrong with the code base of SHVDN with this issue.

If you are creating a script with raw source code without complication, I would think you didn't specify the API version, which fallbacks to use the v2 API in 3.6.0. Fallbacks to v3 in any builds since af0b731933ad4790d0eede52d82eae2bf92b2210 (v3.7.0 will have the same change). You specify the API version for uncompiled scripts like `Script.3.cs`, which will be compiled against the v3 API with `.3` before the extension `.cs` or `.vb`.
