### ISSUE TITLE
[Possible Bug / Possible user error]: 

### ISSUE THREAD

**Issue by AaronWilkesUK** [scripthookvdotnet/scripthookvdotnet#1419]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

3.6

### Game Version

v1.0.1180.2 steam

### Bug Description

Trying to load any script gives an error as follows:

> 
[20:05:25] [DEBUG] Instantiating script Bowling.Bowling ...
[20:05:26] [ERROR] Failed to instantiate script Bowling.Bowling because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.StringToCoTaskMemUTF8(String s)
   at SHVDN.ScriptDomain.PinString(String str)
   at GTA.Native.Function.ObjectToNative(Object value)
   at GTA.Scaleform..ctor(String scaleformID)
   at Bowling.Bowling..ctor()
> 

### Steps To Reproduce

Just installed it, ScriptHook loads the asi but the .net one keeps saying it threw a toy out of its pram

### The Current Behavior

Just not loading and logs that error message

### The Expected Behavior

It should work

**Comment by kagikn** [comment]
Not actionable without further info, but you don't look like you can gather more yourself. Try nightly versions before creating bug report to make sure the error won't happen (but I think I fixed the cause after v3.6.0, maybe wrong though). If you still encounter bugs but don't know how to find the cause, ask someone else to investigate and to create the issue. Remember, bug reports should have how to reproduce in this repository. Unfortunately the error log you posted is doesn't have enough info to investigate, as that the constructor of `SHVDN.NativeMemory` has plenty of calls.

**Comment by AaronWilkesUK** [comment]
It now produces this in the log:

> 
12:24:18] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[12:24:18] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[12:24:18] [DEBUG] Initializing NativeMemory members...
[12:24:19] [DEBUG] Loading scripts from D:\Grand Theft Auto 5\Grand Theft Auto V\scripts ...
[12:24:20] [DEBUG] Loading assembly Bowling.dll ...
[12:24:20] [INFO] Found 3 script(s) in Bowling.dll resolved to API version 2.11.6.
> 

With the .65 nightly, but GTA crashes loading the 3rd picture for story mode

**Comment by kagikn** [comment]
I would say it's not your fault, I guess you're suffering some race conditions (a multithreading term btw) that eventually lead the game to crash. I think SHVDN has some flaws with that, but it wouldn't be easy to completely resolve as race conditions can't be deterministically reproduced.

I'm going to remove the bug label though, because this issue itself doesn't point out what is wrong with SHVDN (that haven't reported before).

**Comment by AaronWilkesUK** [comment]
Yeah, it looks like you already fixed the bug in the nightly's.
Lots of scripts rely on your .NET script hook, is there anything I can do to make it work?  I tried a few other scripts that use the .NET hook and they do the exact same thing, and I tried an earlier nightly, -60 and that has the same, I reinstalled GTA but alas same result, I installed the latest ScriptHookV nothing shows up in the logs saying why it closes.

**Comment by kagikn** [comment]
There's nothing you can do as a user. Only developers who have enough knowledge of multithreading stuff and are willing to read the codebase can address the issue. I would be trying to address again, too.

**Comment by kagikn** [comment]
I'm sure ScriptHookVDotNet.asi causes issues with race conditions, so I think removing all mods in the scripts folder won't be enough to avoid those potential crashes

**Comment by AaronWilkesUK** [comment]
It sits quite happy with no scripts in the folder to load, but that's not very useful, so it must be crashing when loading scripts, is there any way to turn on "extra" logging?

**Comment by kagikn** [comment]
I didn't think of not using auto load, but that is a understandable workaround for nondeterministic compatibility issues, as the more likely updated data applies to caches in other CPU cores the more time elapsed (by getting pushed ouf of cache). I added a new option for the ini config and a console commands for easier manual script loading.

Manual loading scripts won't *more consistently* avoid running scripts letting other SHVDN scripts and the game process touch stale data though. It would be required to make SHVDN scripts running in the same thread and make them run in the same thread as the game logic thread, but difficult to resolve.

> It sits quite happy with no scripts in the folder to load, but that's not very useful, so it must be crashing when loading scripts, is there any way to turn on "extra" logging?

I don't think extra logging is too useful if the error is caused by some race conditions and some piece of game code crashes for access violation. Maybe that is indirectly caused by SHVDN didn't handling multithreading stuff and stale CPU cache that SHVDN lets the game thread touch before updating.

**Comment by AaronWilkesUK** [comment]
Well, just installed the new build and it works without any intervention, game didn't crash and when typing "ListScripts()" it shows several as "Running" so I don't know what you did but I can run it with autoloading scripts!  Thanks
