### ISSUE TITLE
[Bug]: Peds don't hold their guns in map editor !!

### ISSUE THREAD

**Issue by Soru1368** [scripthookvdotnet/scripthookvdotnet#1425]
### What modules are you seeing the problem on?

ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

b5a25a8

### Game Version

1.0.3179.0

### Bug Description

i have a problem with my map editor !! when i set a gun for my peds they don't hold it !! i realized that the ScriptHookVDotNet2 is the issue, i mean in 3.4.0 and higher !! what's wrong ?!!
[ScriptHookV.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/15192692/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/15192693/ScriptHookVDotNet.log)

### Steps To Reproduce

1.updated scripthookvdotnet version to 3.6.0
2.Peds don't hold their weapons in map editor 

### The Current Behavior

it seems that my map editor doesn't work properly with scripthookvdotnet 3.4.0 and higher !! i tried lots of versions and found that the problem is ScriptHookVDotNet2 !! when i use ScriptHookVDotNet.asi and ScriptHookVDotNet3 from 3.4.0 and higher with ScriptHookVDotNet2 from versions like 3.3.2 and lower, there wasn't any problem but when i use ScriptHookVDotNet2 from 3.4.0 and higher the problem with my map editor that i mentioned appears !!

### The Expected Behavior

i explained everything !

**Comment by kagikn** [comment]
As much as I understand why you closed #1424 to try to create a bug report, you should have asked someone else who codes some script if you aren't really sure a bug is responsible to SHVDN and **NOT** SHVDN scripts.

Since oldnapalm's fork of Map Editor calls `WeaponCollection.Give` in [MapEditor.cs](https://github.com/oldnapalm/MapEditor/blob/3bd21330bdfedcb5889d23bc9913e162e789b710/MapEditor.cs#L773), I must clarify one thing, which is, the method **ALWAYS** didn't give any ammo if the ped has the specified weapon in any v2 API versions between v2.10.0 and 2.11.6.0 (that comes with v3.6.0). Despite the behavior not being stated in the API doc, we didn't change the behavior on that after v3.0.0.

**Comment by Soru1368** [comment]
> As much as I understand why you closed #1424 to try to create a bug report, you should have asked someone else who codes some script if you aren't really sure a bug is responsible to SHVDN and **NOT** SHVDN scripts.
> 
> Since oldnapalm's fork of Map Editor calls `WeaponCollection.Give` in [MapEditor.cs](https://github.com/oldnapalm/MapEditor/blob/3bd21330bdfedcb5889d23bc9913e162e789b710/MapEditor.cs#L773), I must clarify one thing, which is, the method **ALWAYS** didn't give any ammo if the ped has the specified weapon in any v2 API versions between v2.10.0 and 2.11.6.0 (that comes with v3.6.0). Despite the behavior not being stated in the API doc, we didn't change the behavior on that after v3.0.0.

first of all i didn't try to create anything, that was a problem with my v2 so i thought that maybe it's a bug !! secondly your answer didn't solve anything, my problem was something else which was not holding the gun by ped !!

**Comment by kagikn** [comment]
I request people not to create bug reports here without providing sufficient steps to reproduce or proof that there's unintended bugs, specifications, or regressions related to the reports that are repsonsible to SHVDN. Without providing such steps or proof, I may not be working to resolve the issues much as they may be responsible to scripts (for their oversights) or how the reporter configured them. I'd like to avoid wasting time by trying to find the causes of an issue reported as a bug of SHVDN only to find it's some oversights or bugs of scripts that's responsible to.

I'm sorry that my previous answer just confused you, although I was explaining one of the reasons why your report didn't tell too well that the bug is responsible to SHVDN.

**Comment by Soru1368** [comment]
> I request people (including you) they should not create bug reports here without providing sufficient steps to reproduce or proof that there's unintended bugs, specifications, or regressions related to the reports that are responsible to SHVDN. Without providing such steps or proof, I may not be working to resolve the issues much as they may be responsible to scripts (for their oversights) or how the reporter configured them. I'd like to avoid wasting time by trying to find the causes of an issue reported as a bug of SHVDN only to find it's some oversights or bugs of scripts that's responsible to. In short: you should create bug reports only if you can tell us sufficient steps to reproduce or proof in the first place.
> 
> I'm sorry that my previous answer just confused you, although I was explaining one of the reasons why your report didn't tell too well that the bug is responsible to SHVDN.

ok no problem, i don't know about these things i just wanted to share my problem. i saw that you put the upgraded version of SHVDN here so i thought that maybe you're responsible for that !!
