### ISSUE TITLE
[Bug]: Doesn't even work and now my game is screwed up

### ISSUE THREAD

**Issue by Hekt1cOfficial** [scripthookvdotnet/scripthookvdotnet#1428]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

0ba28ad

### Game Version

_Unknown_

### Bug Description

Followed the instructions, and now my game won't load. But when I go to my game file folder, none of the files or folders from the zip is in there. Idk what happened or how to fix. L mod smh

### Steps To Reproduce

1. Installed file
2. put all files to game folder
3. crashes

### The Current Behavior

n/a

### The Expected Behavior

Game should launch lol

**Comment by kagikn** [comment]
Edited your post because the report said the SHVDN version you used in the wrong section and didn't said a valid game version like v1.0.3179.0 at all.

While I haven't experienced the same issue until like May 3rd in v1.0.3095.0, I'm suffering it now. I know SHVDN keeps failing to swap the TLS address now, and debugger stopped at this line for `AccessViolationException`:
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/e926124af3ee4d44c49838827bfa528ff8f5abf6/source/core/ScriptDomain.cs#L762

**Comment by kagikn** [comment]
I believe this issue is already resolved as how #1454 got resolved.
