### ISSUE TITLE
Property to check whether we are on the game thread or not

### ISSUE THREAD

**Issue by justalemon** [scripthookvdotnet/scripthookvdotnet#1450]
So I don't have to catch the InvalidOperationException when calling Wait from the wrong thread :)

**Comment by kagikn** [comment]
I don't really think the dedicated property would be worth adding to `GTA.Script` when Unity doesn't provide a property that indicates if the current thread is same as the main thread where you can call Unity APIs.

Instead of catching all `InvalidOperationException`, there's safer way to detect if the current thread id is the id of the *script* main thread, so you won't catch random ones. You store and compare the current thread in a method **other than the script constructor using a lock**, **PER `GTA.Script` instance**. You need to store a thread for each script instance because every script instance has its own native thread. Do not try to store the current thread in script constructors, because SHVDN's script domain calls them in the thread where various SHVDN stuff runs but not for script-specific tasks.
