### ISSUE TITLE
Add a Getter for Ped.BlockPermanentEvents

### ISSUE THREAD

**Issue by tp-mods** [scripthookvdotnet/scripthookvdotnet#1497]
It's possible to read whether a ped is blocking permanent events by checking PedConfigFlag n.17. It would be a good idea to add this to Ped,BlockPermanentEvents as a getter for this property.

**Comment by kagikn** [comment]
Good suggestion. The possible mismatch problem would be that `GetBlockingOfNonTemporaryEvents` of `CPed` (in the game codebase) returns true when `GetBlockingOfNonTemporaryEventsThisFrame` returns true, as well as when the config flag is set. Here's how `GetBlockingOfNonTemporaryEventsThisFrame` is implemented:
```cpp
bool CPed::GetBlockingOfNonTemporaryEventsThisFrame() const
{
    if(ms_bRandomPedsBlockingNonTempEventsThisFrame)
    {
        // `PopTypeIsRandom` returns true when the pop type is between `POPTYPE_RANDOM_PERMANENT` and `POPTYPE_RANDOM_AMBIENT` inclusive.
        // `IsLawEnforcementPed` returns true when the ped type is swat, cop, or army.
        if(PopTypeIsRandom() && !IsLawEnforcementPed())
        {
            return true;
        }
    }

    return false;
}
```
Since I haven't figure out how to access to the static variable `ms_bRandomPedsBlockingNonTempEventsThisFrame` and I'm not really confident if copying `CPed::GetBlockingOfNonTemporaryEvents()`'s behavior is worth it on the getter of our `Ped.BlockPermanentEvents`, I'll implement `Ped.BlockPermanentEvents` just using the config flag.

**Comment by kagikn** [comment]
closing for merging #1498
