### ISSUE TITLE
[Bug]: GTAV won't open with SciptHookVDontNet

### ISSUE THREAD

**Issue by pingarss** [scripthookvdotnet/scripthookvdotnet#1530]
### 📦 What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### 🛠️ SHVDN Version

ad315d5

### 🎮 Game Version

v1.0.3411.0

### 🐛 Bug Description

I tried to use both normal SHVDN and Nightly and both of these when placed in root files, GTAV wont open further than launcher.
![image](https://github.com/user-attachments/assets/eaf7b1ed-728c-4dda-978c-07fad042e648)

### 🔄 Steps To Reproduce

Put in any of the SHVDN files and try to launch the game, it wont open (at least for me)

### ⚠️ Current Behavior

I click to launch the game, open the rockstar launcher, for some seconds it loads and pops out message that the game is running already. When i remove those files, game starts up instantly

### 🎯 Expected Behavior

Game should launch?

**Comment by kagikn** [comment]
Not a bug that's responsible to SHVDN but SHV *v1.0.3407.0*, which happens when you try to launch in GTA V v1.0.3411.0. With SHV *v1.0.34**11**.0*, you can see the game window with SHV mods applied. I have to admit this though, it **is** a very rare case that SHV v1.0.3407.0 doesn't stop the game and shows the infamous ***FATAL: Unknown game version*** message window but still fails to proceed to show the game window in GTA V v1.0.3411.0 (while detecting the game version as *v1.0.34**07**.0*).

**Comment by pingarss** [comment]
I must say that reading my bug report now, it lacks a lot of details. Let me spread it out here.

The issue that is shown on my bug report image only happens if i place either SHDVN normal files in or SHDVN nightly version. I tested out every single item i have put on the root file and the issue only appears when SHDVN is in the root files. 
For example:
1 I start the game with these two added files in:
ScriptHookV.dll
ScriptHookV
Result: game opens almost instantly, no problems, it's playable.
2 But when i put in these files:
ScriptHookVDotNet
ScriptHookVDotNet.pdb
ScriptHookVDotNet2.dll
ScriptHookVDotNet2.pdb
ScriptHookVDotNet3.dll
ScriptHookVDotNet3.pdb
The game goes in to issue that is seen in the picture i added on bug report. So if i understood your response correctly (not a native english speaker), you said that the issue may happen because is have the (1) situation, two SHV files, but in reality the (2) situation makes the game not open
(Yes, when i add SHVN i also have SHV in the root folder)

**Comment by kagikn** [comment]
Can't reproduce the issue with SHV v1.0.3411.0 and SHVDN v3.7.0-nightly.6 in my GTA V v1.0.3411.0. Maybe you're going to have to delete all the files and reinstall again so the game can open with SHVDN if you don't remember all the files you've added (not all launchers necessarily remove files they didn't put to the directory, at least Steam doesn't). You can't really use any released stable versions in the game version v1.0.3258.0 or later because of certain bugs by the way.
