### ISSUE TITLE
Internal versioning of nightly releases

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1539]
Make the assembly version of nightly releases follow [Semantic Versioning](https://semver.org/) by keeping the ''version core'' to 3 dot-separated numbers and adding the nightly info after a hyphen (`-`; eg. `3.7.0-nightly.10`).

**Comment by kagikn** [comment]
Sorry but unacceptable suggestion, because the ctor of `AssemblyName` and the ctor of `Version` that takes a string thows exception when they fail to parse version strings by not following the strict format like "65535.65535.65535.65535", where an delimiter between 2 numbers must be 1 dot character and version numbers must be between 0 and 65535.

Assuming observable behaviors of them are same, here's the line that causes exceptions.
https://github.com/dotnet/runtime/blob/9e28706dbc252e27174dce1a3b8f69c8ecc912b7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L36
https://github.com/dotnet/runtime/blob/9e28706dbc252e27174dce1a3b8f69c8ecc912b7/src/libraries/System.Private.CoreLib/src/System/Version.cs#L68

**Comment by Michael21107** [comment]
@kagikn Understood, thank you anyway.
