### ISSUE TITLE
Usage of fibers causes random .NET runtime crashes

### ISSUE THREAD

**Issue by LMSDev** [scripthookvdotnet/scripthookvdotnet#976]
**Version**
All

**Description**
In its main loop ([ScriptMain](https://github.com/crosire/scripthookvdotnet/blob/main/source/core/DllMain.cpp#L258)), SHVDN makes use of fibers and also calls into unmanaged code implemented using fibers. This is not supported by .NET and will inevitably lead to random crashes, most notably making the .NET exception handler in CLRVectoredExceptionHandler assume that there is no stack space left. The [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-and-unmanaged-threading-in-windows#threads-and-fibers) state "The .NET threading model does not support fibers. You should not call into any unmanaged function that is implemented by using fibers. Such calls may result in a crash of the .NET runtime." With my limited knowledge about the project it is unclear to me why a fiber-based approach was chosen here as it seems like a grave design mistake, but I did not study the entire project.

**Crash Details**
Since a fiber is not its own thread, but behaves like one in certain ways, it has its own stack space. This means that for one thread there will be different stack lower and upper bounds, depending on whether the fiber is running or not. Whenever an exception in .NET occurs, the crash handler in [CLRVectoredExceptionHandler ](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7631) gets called. (I am referencing the initial coreclr commit here as it is closer to what .NET Framework uses than the current .NET core implementation which does not use stack probing at all and hence is not affected). The call to [Thread::IsStackSpaceAvailable](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7763) returns `false` when on a fiber-stack, since its internal call to [GetLastNormalStackAddress](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/threads.cpp#L7912) uses a [cached stack limit](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/threads.cpp#L7269). Naturally this should be using the fiber's stack bounds, but due to the caching it does not. While this is definitely not handled ideally by .NET Framework (and fixed in .NET core), the issue remains that fibers are not supported. Unfortunately, this means that any exception, whether it is a C++ exception as mentioned in #936 or a .NET exception, will cause the runtime to panic and call [DontCallDirectlyForceStackOverflow](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7765), subsequently terminating the process. Please note that this crash does not occur on every machine and seemingly at random, but since I had access to a user machine where it happened on every single exception, it was very easy to debug and pinpoint.

Example stack trace where the offending line is a a NullReferenceException in .NET wrapped by try-catch (which is not hit for the reasons outlined above):
0:000> !dumpstack
OS Thread Id: 0x882c (0)
Current frame: clr!DontCallDirectlyForceStackOverflow+0x10
Child-SP         RetAddr          Caller, Callee
00000011620f31f0 00007ffc7bbe9a11 clr!CLRVectoredExceptionHandler+0xa8, calling clr!DontCallDirectlyForceStackOverflow
00000011620f3220 00007ffc7ba2f96e clr!SaveCurrentExceptionInfo+0x72, calling clr!ClrFlsSetValue
00000011620f3250 00007ffc7ba2fdcf clr!CLRVectoredExceptionHandlerShim+0xa3, calling clr!CLRVectoredExceptionHandler
00000011620f3280 00007ffc97e883dc ntdll!RtlpCallVectoredHandlers+0x108, calling ntdll!guard_dispatch_icall_nop
00000011620f3320 00007ffc97e5b406 ntdll!RtlDispatchException+0x66, calling ntdll!RtlpCallVectoredHandlers
00000011620f3350 00007ffc7b8d882a clr!invokeCompileMethod+0x97, calling clr!invokeCompileMethodHelper
00000011620f33c0 00007ffc7b8d875e clr!CallCompileMethodWithSEHWrapper+0xe5
00000011620f33f0 00007ffc97e25d21 ntdll!RtlFreeHeap+0x51, calling ntdll!RtlpFreeHeapInternal
00000011620f3430 00007ffc7b8c5809 clr!EEHeapFreeInProcessHeap+0x45, calling KERNEL32!HeapFreeStub
00000011620f3460 00007ffc7b8d864d clr!UnsafeJitFunction+0x81b, calling clr!_security_check_cookie
00000011620f3530 00007ffc97eafe3e ntdll!KiUserExceptionDispatch+0x2e, calling ntdll!RtlDispatchException
00000011620f4330 00007ffc1ca6dc66 (MethodDesc 00007ffc1c87e010 +0x26 Rage.Attributes.PluginAttribute.get_Name()) ====> Exception Code c0000005 cxr@00000011620f3540 exr@00000011620f3a30

**Resolution**
I was able to fix this issue by removing the fiber logic from ScriptMain as well as no longer relying on SHV's scriptRegister. Unfortunately, you will have to provide your own script VM tick hook as SHV uses fibers and just removing the fiber logic from SHVDN is not enough. For a simple PoC, I hooked a native and ticked SHVDN from there and it worked fine: no more fiber related crashes! You should be able to still use SHV to receive keyboard callbacks according to my own testing.

If you have any questions or feedback as to why fibers were used (or must be used), please let me know.

**Comment by crosire** [comment]
You have answered the why yourself already :wink:: SHV uses fibers internally, so registering a script through it forces the callback to potentially come back through a fiber, rather than the original thread. Depending on whether this happened or not the CLR will have a bad time. The "solution" that is still in place with a dedicated fiber is essentially just a workaround that happens to work most of the time.
Originally SHVDN did not handle this at all, it just called managed functions from the unmanaged SHV callback directly. This was fine as long as the stack space did not change between callbacks, which was the case most of the time. Unfortunately some actions like loading a save game cause SHV to reload SHVDN and it does so with a different fiber and therefore different stack space then before. The next call into managed code therefore generally crashed pretty quickly. My "solution" back then (https://github.com/crosire/scripthookvdotnet/commit/bf12d5c800cc78ac9475f97d274b5f79e6504a82, like 6 years ago, don't remember the details anymore to be honest) was to ensure SHVDN always calls into managed code from the same fiber. This way on the first managed call the CLR sets itself up in the fiber's stack space and consequent calls are always guaranteed to hit that same space. I did not dig into it much further back then since it seemed to get rid of the problem at hand. The core of SHVDN hasn't really changed all that much since and nobody looked at it again, so the "fix" stuck.
There is no reason fibers must be used though. I can see that the only real solution would be to ditch SHV for script updates. These days this is probably less at odds with the design since more parts of SHVDN have since become independent and rely on direct access to game memory (e.g. the whole `NativeMemory` code). I don't really do work on SHVDN myself anymore though (lost interest in the game), just keeping this repository running and depending on others to update etc., so it's not really an undertaking I would put on myself.

**Comment by LMSDev** [comment]
Thank you for your response. It is unfortunate to hear that you are no longer actively involved, but perhaps another maintainer is willing to give it a shot. I understand that it is not super trivial and might require some time.

**Comment by xiaoxiao921** [comment]
> **Version** All
> 
> **Description** In its main loop ([ScriptMain](https://github.com/crosire/scripthookvdotnet/blob/main/source/core/DllMain.cpp#L258)), SHVDN makes use of fibers and also calls into unmanaged code implemented using fibers. This is not supported by .NET and will inevitably lead to random crashes, most notably making the .NET exception handler in CLRVectoredExceptionHandler assume that there is no stack space left. The [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-and-unmanaged-threading-in-windows#threads-and-fibers) state "The .NET threading model does not support fibers. You should not call into any unmanaged function that is implemented by using fibers. Such calls may result in a crash of the .NET runtime." With my limited knowledge about the project it is unclear to me why a fiber-based approach was chosen here as it seems like a grave design mistake, but I did not study the entire project.
> 
> **Crash Details** Since a fiber is not its own thread, but behaves like one in certain ways, it has its own stack space. This means that for one thread there will be different stack lower and upper bounds, depending on whether the fiber is running or not. Whenever an exception in .NET occurs, the crash handler in [CLRVectoredExceptionHandler ](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7631) gets called. (I am referencing the initial coreclr commit here as it is closer to what .NET Framework uses than the current .NET core implementation which does not use stack probing at all and hence is not affected). The call to [Thread::IsStackSpaceAvailable](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7763) returns `false` when on a fiber-stack, since its internal call to [GetLastNormalStackAddress](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/threads.cpp#L7912) uses a [cached stack limit](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/threads.cpp#L7269). Naturally this should be using the fiber's stack bounds, but due to the caching it does not. While this is definitely not handled ideally by .NET Framework (and fixed in .NET core), the issue remains that fibers are not supported. Unfortunately, this means that any exception, whether it is a C++ exception as mentioned in #936 or a .NET exception, will cause the runtime to panic and call [DontCallDirectlyForceStackOverflow](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/excep.cpp#L7765), subsequently terminating the process. Please note that this crash does not occur on every machine and seemingly at random, but since I had access to a user machine where it happened on every single exception, it was very easy to debug and pinpoint.
> 
> Example stack trace where the offending line is a a NullReferenceException in .NET wrapped by try-catch (which is not hit for the reasons outlined above): 0:000> !dumpstack OS Thread Id: 0x882c (0) Current frame: clr!DontCallDirectlyForceStackOverflow+0x10 Child-SP RetAddr Caller, Callee 00000011620f31f0 00007ffc7bbe9a11 clr!CLRVectoredExceptionHandler+0xa8, calling clr!DontCallDirectlyForceStackOverflow 00000011620f3220 00007ffc7ba2f96e clr!SaveCurrentExceptionInfo+0x72, calling clr!ClrFlsSetValue 00000011620f3250 00007ffc7ba2fdcf clr!CLRVectoredExceptionHandlerShim+0xa3, calling clr!CLRVectoredExceptionHandler 00000011620f3280 00007ffc97e883dc ntdll!RtlpCallVectoredHandlers+0x108, calling ntdll!guard_dispatch_icall_nop 00000011620f3320 00007ffc97e5b406 ntdll!RtlDispatchException+0x66, calling ntdll!RtlpCallVectoredHandlers 00000011620f3350 00007ffc7b8d882a clr!invokeCompileMethod+0x97, calling clr!invokeCompileMethodHelper 00000011620f33c0 00007ffc7b8d875e clr!CallCompileMethodWithSEHWrapper+0xe5 00000011620f33f0 00007ffc97e25d21 ntdll!RtlFreeHeap+0x51, calling ntdll!RtlpFreeHeapInternal 00000011620f3430 00007ffc7b8c5809 clr!EEHeapFreeInProcessHeap+0x45, calling KERNEL32!HeapFreeStub 00000011620f3460 00007ffc7b8d864d clr!UnsafeJitFunction+0x81b, calling clr!_security_check_cookie 00000011620f3530 00007ffc97eafe3e ntdll!KiUserExceptionDispatch+0x2e, calling ntdll!RtlDispatchException 00000011620f4330 00007ffc1ca6dc66 (MethodDesc 00007ffc1c87e010 +0x26 Rage.Attributes.PluginAttribute.get_Name()) ====> Exception Code c0000005 cxr@00000011620f3540 exr@00000011620f3a30
> 
> **Resolution** I was able to fix this issue by removing the fiber logic from ScriptMain as well as no longer relying on SHV's scriptRegister. Unfortunately, you will have to provide your own script VM tick hook as SHV uses fibers and just removing the fiber logic from SHVDN is not enough. For a simple PoC, I hooked a native and ticked SHVDN from there and it worked fine: no more fiber related crashes! You should be able to still use SHV to receive keyboard callbacks according to my own testing.
> 
> If you have any questions or feedback as to why fibers were used (or must be used), please let me know.

What native did you hook ? I'm currently working on a 1:1 BigBaseV2 port to Csharp https://github.com/xiaoxiao921/SharpHost but i'm obviously getting those random crashes you are talking about because it uses fibers all over the place

**Comment by xiaoxiao921** [comment]
Found some by some googling : 

IS_DLC_PRESENT
DOES_CAM_EXIST
DOES_ENTITY_EXIST
GET_NUMBER_OF_EVENTS
IS_ENTITY_UPSIDEDOWN
FRAME_COUNT

**Comment by xiaoxiao921** [comment]
Really confused on how you are supposed to approach this if you can't use fiber at all, how do you approach yielding for example ? Doesn't really seems possible

**Comment by kagikn** [comment]
[Zolika1351’s Trainer](https://www.gta5-mods.com/scripts/zolika1351-s-trainer) doesn’t use SHV’s thread since the version 22.01.29.1. Maybe we could find a way to run SHVDN without SHV’s thread by disassembling the trainer, I guess? Zolika decided not to use SHV’s thread to make the trainer create actual crash dumps, though.

**Comment by kagikn** [comment]
I understand why SHVDN uses a fiber from SHV to run scripts for it. It's because that solution is way more easy than running them in its own ysc script (or whatever Rockstar use internally for their ysc scripts) under a dedicated thread. If we try to resolve this issue, I think we will have to find a way to own a VM script (which is used for ysc scripts) and a way to gather correct native hashes before we can ditch a fiber from SHV the `scriptRegister` call. Maybe we can gather correct native hashes from SHV with memory scanning, though.
I hope those who experience random crashes read this issue and my comments if they have the problem when using both RAGE Plugin Hook (on which LSPDFR depends) and our SHVDN.

**Comment by xiaoxiao921** [comment]
There are alternative to fibers, its just that fibers is a OS ready to go solution that works very well because its well, done by the same team that did the OS so they know a thing or two about their own thread system

Me 1yr+ ago didnt realize much and thought you "had to" use them for some unknown obscure reason, but its not the case, all you want is a mechanism of cooperative thread scheduling, with the ability to give pack execution to someone else and keep track of your stack somewhere so that you can come back at it alter and resume what you were doing, C# has already something for that, its on the msdn doc, now whatever runtime you use for executing c# code hopefully has this mechanism too implemented (its just async / yielding), otherwise it won't work, its by far the cleanest method, there are maybe others, but I didnt dig into it because I moved on other projects

**Comment by kagikn** [comment]
I'm starting to think this issue is worth addressing without other plugins or tools utilizing .NET scripts. Most of the mods made by [RealZolika1351](https://www.gta5-mods.com/users/RealZolika1351) crashes in b2802 or above, and I think this issue is what makes SHVDN incompatible with those (by throwing exceptions and catch them internally I guess).
I think cooperative thread scheduling is irrelevant to this issue btw. That one may be rather related to native performance more than this issue.

**Comment by kagikn** [comment]
I tested if you can retrieve the same value with `GetCurrentThreadId()` via both unmanaged and managed code with this code and it's the game. And I suppose you won't have trouble with TLS thing when you manually mess with `scrThread` or `scrThreadCollection`.
```cpp
#include <msclr/marshal.h>
using namespace System;
using namespace System::Runtime::InteropServices;

value class Win32 {
public:
	[DllImport("Kernel32.dll")]
	static int GetCurrentThreadId();
};

unsigned int GetCurrentThreadIdViaManagedCode()
{
	unsigned int a = Win32::GetCurrentThreadId();
	return a;
}

#pragma unmanaged
#include <iostream>
#include <windows.h>

int main()
{
	unsigned int a = GetCurrentThreadId();
	unsigned int b = GetCurrentThreadIdViaManagedCode();

	std::wcout << a << std::endl;
	std::wcout << b << std::endl;

	return 0;
}
```

**Comment by Sardelka9515** [comment]
> I understand why SHVDN uses a fiber from SHV to run scripts for it. It's because that solution is way more easy than running them in its own ysc script (or whatever Rockstar use internally for their ysc scripts) under a dedicated thread. 

There's an open source implementation of ScriptHookV called OpenVHook, maybe we can take a look on how they [create a script thread](https://github.com/ivanmeler/OpenVHook/blob/a0b331ae28733a5b8ae3f2772308e5f2b5e10cf7/OpenVHook/Scripting/ScriptEngine.cpp#L343). 
It might be outdated, but [fivem won't](https://github.com/citizenfx/fivem/blob/master/code/components/scripting-gta/src/ScriptEngine.cpp), on which OpenVHook is based.

We probably don't need to ditch SHV entirely, though, its native call api should still work when running in different thread.

**Comment by Sardelka9515** [comment]
> I'm starting to think this issue is worth addressing even without thinking about other plugins or tools utilizing .NET code other than SHVDN. 

Yes , exception handling is completely broken with SHVDN running. Just one c++ exception, catched or not, crash the script or the entire game badly.

**Comment by kagikn** [comment]
> > I understand why SHVDN uses a fiber from SHV to run scripts for it. It's because that solution is way more easy than running them in its own ysc script (or whatever Rockstar use internally for their ysc scripts) under a dedicated thread.
> 
> There's an open source implementation of ScriptHookV called OpenVHook, maybe we can take a look on how they [create a script thread](https://github.com/ivanmeler/OpenVHook/blob/a0b331ae28733a5b8ae3f2772308e5f2b5e10cf7/OpenVHook/Scripting/ScriptEngine.cpp#L343). It might be outdated, but [fivem won't](https://github.com/citizenfx/fivem/blob/master/code/components/scripting-gta/src/ScriptEngine.cpp), on which OpenVHook is based.
> 
> We probably don't need to ditch SHV entirely, though, its native call api should still work when running in different thread.

It looks like we can really call SHV's native call api when running in a different thread. Test code is here:
```C++
void CanCallSHVNativeInit()
{
    uintptr_t gameStatePtr;
    while (true) {
        auto gameStateAddr = FindPattern("D1 E9 F6 C1 01 75 19 8B");
        if (gameStateAddr) {
            gameStatePtr = *(int32_t*)(gameStateAddr + 9) + gameStateAddr + 13;
            break;
        }
        else {
            Sleep(5000);
        }
    }

    Sleep(10000); // I guess you have to wait for SHV to prepare its own native context

    while (true) {
        // as long as this game state is initialized, it would be safe SHV has prepared its own native context in some casual test
        if (*(uint32_t*)gameStatePtr == 0) {
            break;
        }
        else {
            Sleep(1000);
        }
    }

    auto nativeInitFuncAddr = FindPattern("48 89 5C 24 08 57 48 83 EC 20 48 8B F9 E8 ? ? ? ? 48 ? D8 48", L"ScriptHookV.dll"); // this one should be able to find the function with all SHV versions
    auto nativeCallFuncAddr = FindPattern("85 C0 74 46 4C", L"ScriptHookV.dll"); // this one is poorly created and didn't find the function with SHV for up to b350
    if (nativeInitFuncAddr && nativeCallFuncAddr) {
        typedef double (*nativeInit_t)(uint64_t);
        typedef uintptr_t (*nativeCallFunc_t)(void);
        auto nativeInit = ((nativeInit_t)nativeInitFuncAddr)(0xD80958FC74E988A6); // call PLAYER_PED_ID
        auto playerPedId = *(uint32_t*)(((nativeCallFunc_t)(nativeCallFuncAddr - 0x17))());

        std::ofstream writing_file("SHVFuncCallFromAnotherDLL.txt");
        writing_file << "playerPedId " << playerPedId << std::endl; // playerPedId should be 2
        writing_file.flush();
        writing_file.close();
    } else {
        std::ofstream writing_file("SHVFuncCallFromAnotherDLL.txt");
        writing_file << "Couldn't call a native" << std::endl;
        writing_file.flush();
        writing_file.close();
    }
}

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        CreateThread(NULL, NULL, (LPTHREAD_START_ROUTINE)CanCallSHVNativeInit, hModule, NULL, NULL);
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

**Comment by Sardelka9515** [comment]
If the native is called from a ysc script thread, TLS stuff should be handled by the game itself? Will using own native context make a difference?

**Comment by kagikn** [comment]
I don't exactly know TLS stuff is handled by the game on ysc script threads, but I think that's the case as long as you set a thread properly like this. https://github.com/citizenfx/fivem/blob/4b01351f0e56314e55d0e6ab7f21458cc2e6606c/code/components/rage-scripting-five/src/scrEngine.cpp#L231
However, you can't even successfully call any natives that uses TLS stuff if not set the active thread properly, it will result in the game crash even if you don't have SHVDN installed. This is a example snippet:
```
while (true) {
    // as long as this game state is initialized, it would be safe SHV has prepared its own native context in some casual test
    if (*(uint32_t*)gameStatePtr == 0) {
        break;
    }
    else {
        Sleep(1000);
    }
}
/// the code below will be executed as soon as you can control the player ped

auto nativeInitFuncAddr = FindPattern("48 89 5C 24 08 57 48 83 EC 20 48 8B F9 E8 ? ? ? ? 48 ? D8 48", L"ScriptHookV.dll");
auto nativePushFuncAddr = FindPattern("8B 15 ? ? ? ? 48 8B 05 ? ? ? ? 48 89 0C D0 FF 05 ? ? ? ? C3", L"ScriptHookV.dll");
auto nativeCallFuncAddr = FindPattern("85 C0 74 46 4C", L"ScriptHookV.dll");
if (nativeInitFuncAddr && nativePushFuncAddr && nativeCallFuncAddr) {
    typedef void (*nativeInit_t)(uint64_t);
    typedef void (*nativePush_t)(uint64_t);
    typedef uintptr_t(*nativeCallFunc_t)(void);

    ((nativeInit_t)nativeInitFuncAddr)(0xF6A9D9708F6F23DF); // START_ENTITY_FIRE. This native uses TLS stuff!
    ((nativePush_t)nativePushFuncAddr)(2); // 2 will be the initial player ped id
    (((nativeCallFunc_t)(nativeCallFuncAddr - 0x17))());
    // what you might expect: the player ped staggers and creates a fire particle
    // actual: just makes the player ped staggers and crashes the game soon
}
```

**Comment by Sardelka9515** [comment]
Oh, that makes sense.

>Looks like you can retrieve the native handler with the memory pattern for nativeInitFuncAddr though (the first function that will be called by nativeInit). You can use the first native hashes present in the game (not updated ones)

Interesting, this way we should be able to find the hashmap that SHV uses to store the handlers?

Then hooking to a native handler should be probably be easier than creating a ysc thread/dealing with TLS stuff.

**Comment by kagikn** [comment]
I found a way to inspect the VTable of `GtaThread`. You can find the ctor call with `7E 36 ? 8B ? B9 ? ? 00 00 E8 ? ? ? ? 48 85 C0` (+ 5 bytes). We could swap the virtual function for ticking on our own GtaThread instance so we can call the tick function in SHVDN. The offset for the tick function of GtaThread is 0x18 (not changed between b372 to b2824).

**Comment by Sardelka9515** [comment]
> The offset for the tick function of `GtaThread` is 0x18 (not changed between b372 to b2824).

This function?
https://github.com/ivanmeler/OpenVHook/blob/a0b331ae28733a5b8ae3f2772308e5f2b5e10cf7/OpenVHook/Scripting/ScriptThread.cpp#L8

**Comment by kagikn** [comment]
> > The offset for the tick function of `GtaThread` is 0x18 (not changed between b372 to b2824).
> 
> This function? https://github.com/ivanmeler/OpenVHook/blob/a0b331ae28733a5b8ae3f2772308e5f2b5e10cf7/OpenVHook/Scripting/ScriptThread.cpp#L8

Yes, but you'll need to replace the 3rd byte with `?` due to the layout change of `GtaThread` in b2699, like this memory pattern.
https://github.com/citizenfx/fivem/blob/f9578a0c545cd8e3f76c7777118e698e1c39a849/code/components/rage-scripting-five/src/scrThread.cpp#L40

**Comment by DottieDot** [comment]
TLS stands for Thread Local Storage, and the currently active script isn't the only thing stored in it. The native `WORLDPROBE::START_SHAPE_TEST_BOX` will *probably* crash with your implementation. 

Additionally, natives aren't thread safe, which can cause hard-to-diagnose bugs and crashes. For example, `GET_FILENAME_FOR_AUDIO_CONVERSATION` (used to be `_GET_LABEL_TEXT`) will store its result in a shared buffer, you'd get weird and unpredictable results if this native were to be called by two threads simultaneously.

**Comment by kagikn** [comment]
> TLS stands for Thread Local Storage, and the currently active script isn't the only thing stored in it. The native `WORLDPROBE::START_SHAPE_TEST_BOX` will _probably_ crash with your implementation.
> 
> Additionally, natives aren't thread safe, which can cause hard-to-diagnose bugs and crashes. For example, `GET_FILENAME_FOR_AUDIO_CONVERSATION` (used to be `_GET_LABEL_TEXT`) will store its result in a shared buffer, you'd get weird and unpredictable results if this native were to be called by two threads simultaneously.
> 
> EDIT: This was a reply to [#976 (comment)](https://github.com/crosire/scripthookvdotnet/issues/976#issuecomment-1425415336)

I wasn't even considering thread-safe concept since you can immediately crash with one native call that use TLS (yes, that naive example), but I'm wondering it is safe to share a native context among multiple external scripts (not ysc scripts) now. SHVDN doesn't run scripts for it simultaneously and scripts will wait until the time comes, but it shares its native context among them. I haven't watched if a RPH plugin uses the same native context with other plugins yet btw.
https://github.com/crosire/scripthookvdotnet/blob/712bad29175b0bd50e2d9ae7c12086c0ec6801e8/source/core/ScriptDomain.cs#L585

**Comment by DottieDot** [comment]
> I wasn't even considering the thread safety concept since you can immediately crash with one native call that use TLS (yes, that naive example), but I'm wondering it is safe to share a script context among multiple external scripts (not ysc scripts) now. SHVDN doesn't run scripts for it simultaneously and scripts will wait until the time comes, but it shares its script context among them. I haven't checked if a RPH plugin uses the same script context with other plugins yet btw.
> 
> https://github.com/crosire/scripthookvdotnet/blob/712bad29175b0bd50e2d9ae7c12086c0ec6801e8/source/core/ScriptDomain.cs#L585

I'm assuming that with "script context" you mean `rage::scrThread`/`GtaThread`?

There shouldn't be any real issues with reusing them, in fact most (all?) hooks for GTA Online simply hook a native and hijack ysc script thread. There are some natives that will modify properties of the current script like `SET_THIS_SCRIPT_CAN_REMOVE_BLIPS_CREATED_BY_ANY_SCRIPT` and `SET_THIS_SCRIPT_CAN_BE_PAUSED`, but that's generally not considered important.

**Comment by kagikn** [comment]
> > I wasn't even considering the thread safety concept since you can immediately crash with one native call that use TLS (yes, that naive example), but I'm wondering it is safe to share a script context among multiple external scripts (not ysc scripts) now. SHVDN doesn't run scripts for it simultaneously and scripts will wait until the time comes, but it shares its script context among them. I haven't checked if a RPH plugin uses the same script context with other plugins yet btw.
> > https://github.com/crosire/scripthookvdotnet/blob/712bad29175b0bd50e2d9ae7c12086c0ec6801e8/source/core/ScriptDomain.cs#L585
> 
> I'm assuming that with "script context" you mean `rage::scrThread`/`GtaThread`?
> 
> There shouldn't be any real issues with reusing them, in fact most (all?) hooks for GTA Online simply hook a native and hijack ysc script thread. There are some natives that will modify properties of the current script like `SET_THIS_SCRIPT_CAN_REMOVE_BLIPS_CREATED_BY_ANY_SCRIPT` and `SET_THIS_SCRIPT_CAN_BE_PAUSED`, but that's generally not considered important.

Yes, I meant `rage::scrThread`/`GtaThread`. So reusing those thread will never be a serious problem and would cause only negligible problems if any. I appriciate your info about reusing them and the fact most (all?) hooks for GTA Online simply.

**Comment by Sardelka9515** [comment]
> > > The offset for the tick function of `GtaThread` is 0x18 (not changed between b372 to b2824).
> > 
> > 
> > This function? https://github.com/ivanmeler/OpenVHook/blob/a0b331ae28733a5b8ae3f2772308e5f2b5e10cf7/OpenVHook/Scripting/ScriptThread.cpp#L8
> 
> Yes, but you'll need to replace the 3rd byte with `?` due to the layout change of `GtaThread` in b2699, like this memory pattern. https://github.com/citizenfx/fivem/blob/f9578a0c545cd8e3f76c7777118e698e1c39a849/code/components/rage-scripting-five/src/scrThread.cpp#L40

Tried hooking this function, but it appears it was only called from SHV(same script hash and thread id)

**Comment by kagikn** [comment]
Okay, I think I found how RPH ticks. It looks like RPH hooks this function by overwriting with `mov rax, rockstarupdater.dll+(some offset)` and `jmp rax`, which makes all script threads run if my speculation is correct. https://github.com/YimMenu/YimMenu/blob/d663d9517cd894e7d1687e6441736ec9127998ed/src/pointers.cpp#L78
At least SHV doesn't hook that function, but it utilizes `START_NEW_SCRIPT` (it also uses `audiotest` ysc script where no practical opcode is present) and `IS_THREAD_ACTIVE` (probably uses more native functions for scripts).
`rockstarupdater.dll` will be generated at runtime btw.

**Comment by Sardelka9515** [comment]
#977 Does not happen if there's no fiber switching in `ScriptMain`, but the game crashes after loading a save game

**Comment by Sardelka9515** [comment]
I think I found a way to avoid the crash through some tricky managed/unmanaged transition. #1167

**Comment by kagikn** [comment]
Closing this issue since we think #1167 solves, but feel free to reopen if the issue persists even with #1167 applied as long as sufficient information is provided to explain why the issue persists.

**Comment by kagikn** [comment]
Closing this issue since we think #1167 solves, but If the issue persists even with the PR applied, feel free to reopen as long as sufficient information is provided to explain why the issue persists.

**Comment by kagikn** [comment]
Reopening this issue because we realized some minor issues occurs as #1169 explains since #1167 was merged and I think this one is not completely solved.

**Comment by kagikn** [comment]
Reopening as not completely resolved. After being closed as completed for 5 months later, I found SHVDN does crash the game sometimes when it gets loaded. Always crashes after SHVDN logs `Loading API from` lines in my environment in that case.
I haven't spot where the crash may happen, but I believe it's probably from some assembly code in a vector exception handler in clr.dll (I think LMS knows this issue happens from a VEH of .NET runtime, even the log at the first post contains). `launcher.log` in `%CSIDL_MYDOCUMENTS%\Rockstar Games` logs `[gamelaunch] Game exited with code 0xc00000fd (3221225725)` when said crash happens. 0xc00000fd indicates stack overflow according to the document of [NTSTATUS Values](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55).

For end-users, v3.7.0 will contain a partial "fix" where stack position cache issue is somehow partially relaxed. .NET runtime wouldn't crash every time C++ scripts tries to catch a exception or RAGE Plugin Hook tries to catch an unhandled exception (probably uses [try-except statement](https://learn.microsoft.com/en-us/cpp/cpp/try-except-statement?view=msvc-170) since it can even catch access violation in unmanaged code). this issue can happen only when a [vector exception handler](https://learn.microsoft.com/en-us/windows/win32/debug/vectored-exception-handling) of .NET runtime catches something (VEH takes precedence over SEH in exception handling), I am sure that this issue won't completely randomly occur.

**Comment by kagikn** [comment]
ScriptHookV runtime itself uses a dedicated thread different for a fiber than the main thread where most game logic is executed. Interesting fact is, SHV scripts get executed in the main thread with pieces of fiber data. I spot the fact with x64dbg and TIB of the main thread (named "TEB" in Threads tab in x64dbg) can have a value other than 0x1E00 if some SHV script is running, which indicates there's a real fiber data. We can just hope hooking the function for script ticking will do the job to avoid using some of SHV's fibers. Maybe instead we have to hook the equivalent function of [GetLastNormalStackAddress](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/threads.cpp#L7832C18-L7832C43) in some .NET dll to always fetch the fresh value of the lower stack bound, though.

**Comment by Sardelka9515** [comment]
Another (less hacky) option is to run the CLR in a separate thread, performance impact should be negligible since the natives can now be called safely by swapping TLS pointer. Had a PR that did this a while back.

**Comment by kagikn** [comment]
Ah, I just remembered you made #1181 . Since it wasn't mentioned that you can close a thread handle (to avoid thread handle leak that will result in the thread persistence iirc) in that PR, maybe there's only a few things that should be changed and we can reuse majority of it? For thread handle leak, I have a few cases to show. https://github.com/Lyall/IshinFix/issues/5 https://github.com/kagikn/ExeIntegrityBypassAgainstRGL/blob/40c18129692a5316ff0634a1ce736092bb765769/ExeIntegrityBypassAgainstRGL/dllmain.cpp#L145
